[package]
name = "ragec-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
ragec-lexer = { path = "../ragec-lexer" }
ragec-parser = { path = "../ragec-parser" }
ragec-token = { path = "../ragec-token" }
