[package]
name = "ragea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ragea-cli = { path = "../ragea-cli" }
ragea-lib = { path = "../ragea-lib" }
